In [1]:
from pathlib import Path
import os
import numpy as np
import pandas as pd
import random 

mids_dir = Path("D:\\MIDS-W207")
data = mids_dir/"MIDS-W207-Spring24-Soccer-Detection-Data"
project = mids_dir/"MIDS-W207-Spring24-Soccer-Detection"
analysis = project/"analysis"

# Author: Timothy Majidzadeh
# Date Created: March 4, 2024
# Date Updated: March 4, 2024
# Description: Develop the label import script.
# Notes: [v1] Created program.
# Inputs: Data label CSV files.
# Outputs: Stacked & reshaped CSV file.

In [2]:
def load_and_label(dir, filename):
    """
    Loads the CSV file at path, returning it as a dataframe with the sourcefile as a column.
    Inputs:
        A path to a CSV with the bounding boxes for images.
    Outputs:
        A Pandas DataFrame with the loaded & cleaned CSV.
    """
    raw = pd.read_csv(dir/filename, header=[0, 1, 2])[1:].reset_index()
    raw.rename(columns={"index": "frame", "0" : "team_0", "1" : "team_1", "BALL": "ball"}, level=0, inplace=True)
    raw.rename(columns={
        "0" : "player_00",
        "1" : "player_01",
        "2" : "player_02",
        "3" : "player_03",
        "4" : "player_04",
        "5" : "player_05",
        "6" : "player_06",
        "7" : "player_07",
        "8" : "player_08",
        "9" : "player_09",
        "10" : "player_10",
        "11" : "player_11",
        "BALL" : "ball"
    }, level=1, inplace=True)
    raw.drop(columns="TeamID", inplace=True, level=0)
    raw['filename'] = filename.replace(".csv", "")
    raw.set_index(["filename", "frame"], inplace=True)
    return raw

In [12]:
top_view_input = data/"untouched/top_view_labels"
top_view_output = data/"base/top_view_labels"
wide_view_input = data/"untouched/wide_view_labels"
wide_view_output = data/"base/wide_view_labels"

In [13]:
stacked_data = pd.concat([load_and_label(top_view_input, filename) for filename in os.listdir(top_view_input)])
stacked_data.to_csv(top_view_output/"top_view_labels.csv")
stacked_data.to_pickle(top_view_output/"top_view_labels.pkl")

In [14]:
stacked_data = pd.concat([load_and_label(wide_view_input, filename) for filename in os.listdir(wide_view_input)])
stacked_data.to_csv(wide_view_output/"wide_view_labels.csv")
stacked_data.to_pickle(wide_view_output/"wide_view_labels.pkl")

In [15]:
stacked_data

                                team_0                                     \
                             player_00                          player_01
                             bb_height bb_left  bb_top bb_width bb_height
filename               frame
F_20200220_1_0000_0030 1          32.0  4270.0  538.00     16.0      35.0
                       2          32.0  4270.0  537.75     16.0      35.5
                       3          32.0  4270.0  537.50     16.0      36.0
                       4          32.0  4270.0  537.25     16.0      37.0
                       5          32.0  4270.0  537.00     16.0      36.0
...                                ...     ...     ...      ...       ...
F_20220220_1_1950_1980 746        36.0  4113.0  530.00     27.0      34.0
                       747        36.0  4113.0  530.00     27.0      34.0
                       748        36.0  4113.0  530.00     27.0      34.0
                       749        36.0  4113.0  530.00     27.0      34.0
                       750        36.0  4113.0  530.00     27.0      34.0

                                                                        ...  \
                                                     player_10          ...
                             bb_left bb_top bb_width bb_height bb_left  ...
filename               frame                                            ...
F_20200220_1_0000_0030 1      3830.0  524.0     11.0      32.0  3526.0  ...
                       2      3828.5  523.5     11.0      32.0  3525.0  ...
                       3      3827.0  523.0     11.0      32.0  3524.5  ...
                       4      3827.0  523.0     11.0      32.0  3524.0  ...
                       5      3827.0  523.0     11.0      32.0  3523.5  ...
...                              ...    ...      ...       ...     ...  ...
F_20220220_1_1950_1980 746    3611.0  509.0     19.0      43.0  3290.0  ...
                       747    3611.0  509.0     19.0      43.0  3289.0  ...
                       748    3611.0  509.0     19.0      43.0  3288.0  ...
                       749    3611.0  509.0     19.0      43.0  3287.0  ...
                       750    3611.0  509.0     19.0      43.0  3287.0  ...

                                team_1                                         \
                             player_08          player_09
                                bb_top bb_width bb_height      bb_left bb_top
filename               frame
F_20200220_1_0000_0030 1         497.0     15.0      37.0  3124.000000  506.0
                       2         497.0     15.0      37.0  3125.000000  506.0
                       3         497.0     15.0      37.0  3125.076923  506.0
                       4         497.0     15.0      37.0  3125.153846  506.0
                       5         497.0     15.0      37.0  3125.230769  506.0
...                                ...      ...       ...          ...    ...
F_20220220_1_1950_1980 746       496.0     16.0      62.0  2851.000000  582.0
                       747       496.0     16.0      62.0  2849.000000  582.0
                       748       496.0     16.0      62.0  2846.000000  583.0
                       749       496.0     16.0      62.0  2844.000000  583.0
                       750       496.0     16.0      62.0  2842.000000  584.0

                                           ball
                                           ball
                             bb_width bb_height bb_left bb_top bb_width
filename               frame
F_20200220_1_0000_0030 1         14.0       7.0  3542.0  549.0      6.0
                       2         14.0       7.0  3548.0  549.0      6.0
                       3         14.0       7.0  3554.0  549.0      6.0
                       4         14.0       7.0  3560.0  549.0      6.0
                       5         14.0       7.0  3565.0  549.0      6.0
...                               ...       ...     ...    ...      ...
F_20220220_1_1950_1980 746       40.0       7.0  3162.0  509.0      7.0
                       747       40.0       6.0  3165.0  508.0      7.0
                       748       40.0       6.0  3168.0  508.0      7.0
                       749       40.0       6.0  3171.0  508.0      7.0
                       750       41.0       6.0  3174.0  508.0      7.0

[49500 rows x 92 columns]

In [16]:
top_view_labels = pd.read_pickle(data/"base/top_view_labels/top_view_labels.pkl")
top_view_labels

                                team_0                                      \
                             player_00                           player_01
                             bb_height bb_left   bb_top bb_width bb_height
filename               frame
D_20220220_1_0000_0030 1          39.0  801.00  1051.00     39.0      39.0
                       2          39.0  801.75  1052.25     39.0      39.0
                       3          39.0  802.50  1053.50     39.0      39.0
                       4          39.0  803.25  1054.75     39.0      39.0
                       5          39.0  804.00  1056.00     39.0      39.0
...                                ...     ...      ...      ...       ...
D_20220220_1_1770_1800 896        38.0  991.00  1064.00     48.0      38.0
                       897        38.0  991.25  1064.00     48.0      38.0
                       898        38.0  991.50  1064.00     48.0      38.0
                       899        38.0  991.75  1064.00     48.0      38.0
                       900        38.0  992.00  1064.00     48.0      38.0

                                                                               \
                                                           player_10
                             bb_left       bb_top bb_width bb_height  bb_left
filename               frame
D_20220220_1_0000_0030 1      1464.0  1080.000000     39.0      39.0  1920.00
                       2      1464.0  1079.692308     39.0      39.0  1917.25
                       3      1464.0  1079.384615     39.0      39.0  1914.50
                       4      1464.0  1079.076923     39.0      39.0  1911.75
                       5      1464.0  1078.769231     39.0      39.0  1909.00
...                              ...          ...      ...       ...      ...
D_20220220_1_1770_1800 896    1742.5  1171.500000     38.0      38.0  2270.00
                       897    1743.0  1171.000000     38.0      38.0  2271.00
                       898    1743.0  1170.500000     38.0      38.0  2272.00
                       899    1743.0  1170.000000     38.0      38.0  2273.00
                       900    1744.0  1170.000000     38.0      38.0  2274.00

                              ...       team_1                     \
                              ...    player_08          player_09
                              ...       bb_top bb_width bb_height
filename               frame  ...
D_20220220_1_0000_0030 1      ...  1364.000000     39.0      39.0
                       2      ...  1363.975610     39.0      39.0
                       3      ...  1363.951220     39.0      39.0
                       4      ...  1363.926829     39.0      39.0
                       5      ...  1363.902439     39.0      39.0
...                           ...          ...      ...       ...
D_20220220_1_1770_1800 896    ...  1564.000000     40.0      40.0
                       897    ...  1568.000000     40.0      40.0
                       898    ...  1572.000000     40.0      40.0
                       899    ...  1576.000000     40.0      40.0
                       900    ...  1580.000000     40.0      40.0

                                                                     ball  \
                                                                     ball
                                  bb_left       bb_top bb_width bb_height
filename               frame
D_20220220_1_0000_0030 1      2537.000000  1146.000000     39.0     10.00
                       2      2536.857143  1145.714286     39.0      9.75
                       3      2536.714286  1145.428571     39.0      9.50
                       4      2536.571429  1145.142857     39.0      9.25
                       5      2536.428571  1144.857143     39.0      9.00
...                                   ...          ...      ...       ...
D_20220220_1_1770_1800 896    2450.000000  1366.000000     50.0     13.00
                       897    2453.000000  1368.000000     50.0     13.00
                       898    2456.000000  1369.000000     50.0     13.00
                       899    2459.000000  1370.000000     50.0     13.00
                       900    2462.000000  1372.000000     50.0     13.00



                                  bb_left       bb_top bb_width
filename               frame
D_20220220_1_0000_0030 1      1916.000000  1073.000000    10.00
                       2      1910.750000  1073.750000     9.75
                       3      1905.500000  1074.500000     9.50
                       4      1900.250000  1075.250000     9.25
                       5      1895.000000  1076.000000     9.00
...                                   ...          ...      ...
D_20220220_1_1770_1800 896    2737.571429   882.857143    15.00
                       897    2735.428571   882.142857    15.00
                       898    2733.285714   881.428571    15.00
                       899    2731.142857   880.714286    15.00
                       900    2729.000000   880.000000    15.00

[54023 rows x 92 columns]